# Generated by Django 6.0.2 on 2026-03-01 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiagent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='agent_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
