# Generated by Django 6.0.2 on 2026-03-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiagent', '0003_userprofile_full_name_userprofile_preferred_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
