# Generated by Django 6.0.2 on 2026-03-02 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiagent', '0004_alter_userprofile_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutriuser',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_individuals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nutriuser',
            name='role',
            field=models.CharField(choices=[('user', 'Individual User'), ('vht', 'Village Health Team')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
